FROM node:18-alpine

LABEL maintainer="Sigmasolutions"


ARG VUE_APP_META_MANAGER_BASE_URL
ENV VUE_APP_META_MANAGER_BASE_URL $VUE_APP_META_MANAGER_BASE_URL

WORKDIR /build

COPY . ./
RUN npm install && npm run generate


FROM nginx:stable-alpine

RUN rm -rf /var/www/html/*
WORKDIR /var/www/html

COPY hacks/docker/nginx.conf /etc/nginx/nginx.conf
COPY hacks/docker/site.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /build/.output/public /var/www/html

RUN chown -R nginx:nginx .
