<template>
  <div class="px-10 sm:px-20">
    <div class="bg-[#150947] text-center text-white mt-10 text-2xl py-1">
      Privacy Policy
    </div>
    <p class="h-[65vh] overflow-y-scroll bg-gray-200 rounded">
      Sigma Solution (“us”, “we”, or “our”) operates the Sigma Solutions Bd.
      Your privacy is important to us. Sigma Solutions is committed to respect
      your privacy while using our website. This Policy defines the requirements
      to ensure compliance with the applicable data privacy laws and regulations
      applicable to Sigma Solutions’ collection, use, and transmission of
      Personal Data for information collected by us on our website. We use your
      data to provide and improve the Service. By using the Service, you agree
      to the collection and use of information in accordance with this policy.
      Definitions Services: Service means the website Sigma Solutions Bd
      operated by Sigma Solutions. Personal Data : Personal Data means data
      about a living individual who can be identified from those data (or from
      those and other information either in our possession or likely to come
      into our possession). Usage Data: Usage Data is data collected
      automatically either generated by the use of the Service or from the
      Service infrastructure itself (for example, the duration of a page visit)
      Cookies: Usage Cookies are small files stored on your device (computer or
      mobile device) Data Controller : Data Controller means the natural or
      legal person who (either alone or jointly or in common with other persons)
      determines the purposes for which and the manner in which any personal
      information are, or are to be, processed. For the purpose of this Privacy
      Policy, we are a Data Controller of your Personal Data Data Processors (or
      Service Providers): Data Processor (or Service Provider) means any natural
      or legal person who processes the data on behalf of the Data Controller.
      We may use the services of various Service Providers in order Data Subject
      (or User): Data Subject is any living individual who is using our Service
      and is the subject of Personal Data Types of Data Collected Personal Data
      : While using our Service, we may ask you to provide us with certain
      personally identifiable information that can be used to contact or
      identify you (“Personal Data”). Personally, identifiable information may
      include, but is not limited to: Email address; First name; and last name
      Phone number We may use your Personal Data to contact you with
      newsletters, marketing or promotional materials and other information that
      may be of interest to you. You may opt out of receiving any, or all, of
      these communications from us by following the unsubscribe link or the
      instructions provided in any email we send Usage Data: We may also collect
      information that your browser sends whenever you visit our Service or when
      you access the Service by or through a mobile device (“Usage Data”). and
      date of your visit, the time spent on those pages, unique device
      identifiers and other diagnostic data. When you access the Service with a
      mobile device, this Usage Data may include information such as the type of
      mobile device you use, your mobile device unique ID, the IP address of
      your mobile device, your mobile operating system, the type of mobile
      Internet browser you use, unique device identifiers and other diagnostic
      data Use of Data To provide and maintain our Service To notify you about
      changes to our Service To allow you to participate in interactive features
      of our Service when you choose to do so To provide customer support To
      gather analysis or valuable information so that we can improve our Service
      To monitor the usage of our Service To detect, prevent and address
      technical issues To provide you with news, special offers and general
      information about other goods, services, and events which we offer that
      are similar to those that you have already purchased or enquired about
      unless you have opted not to receive such information Retention of Data
      Sigma Solutions will retain your Personal Data only for as long as is
      necessary for the purposes set out in this Privacy Policy. We will retain
      and use your Personal Data to the extent necessary to comply with our
      legal obligations (for example, if we are required to retain your data to
      comply with applicable laws), resolve disputes and enforce our legal
      agreements and policies. Sigma Solutions will also retain Usage Data for
      internal analysis purposes. Usage Data is generally retained for a shorter
      period of time, except when this data is used to strengthen the security
      or to improve the functionality of our Service, or we are legally
      obligated to retain this data for longer periods Disclosure of Data
      Business Transaction : If Sigma Solutions is involved in a merger,
      acquisition or asset sale, your Personal Data may be transferred. We will
      provide notice before your Personal Data is transferred and becomes
      subject to a different Privacy Policy Disclosure for Law Enforcement :
      Under certain circumstances, Sigma Solutions may be required to disclose
      your Personal Data if required to do so by law or in response to valid
      requests by public authorities (e.g., a court or a government agency)
      Legal Requirements : Sigma Solutions may disclose your personal data in
      the good faith belief that such action is necessary to: To comply with a
      legal obligation To protect and defend the rights or property of Sigma
      Solutions To prevent or investigate possible wrongdoing in connection with
      the Service To protect the personal safety of users of the Service or the
      public To protect against legal liability Security of Data The security of
      your data is important to us but remember that no method of transmission
      over the Internet or method of electronic storage is 100% secure. While we
      strive to use commercially acceptable means to protect your Personal Data,
      we cannot guarantee its absolute security Changes in Privacy Policy We may
      update our Privacy Policy from time to time. We will notify you of any
      changes by posting the new Privacy Policy on this page. We will let you
      know via email and/or a prominent notice on our Service, prior to the
      change becoming effective and update the “effective date” at the top of
      this Privacy Policy. You are advised to review this Privacy Policy
      periodically for any changes. Changes to this Privacy Policy are effective
      when they are posted on this page
    </p>
  </div>
</template>
<script>
export default {
  layout: 'login',
  // OR
}
</script>
